---
name: DBIx-Class-DynamicSubclass
version: 0.01
author: []
abstract: Convenient way to use dynamic subclassing.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBIx::Class: 0.07003
build_requires:
  DBD::SQLite: 1.11
provides:
  DBIx::Class::DynamicSubclass:
    file: lib/DBIx/Class/DynamicSubclass.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
